import type { DemoCustomer } from "./types";

export const demoCustomers: DemoCustomer[] = [
  {
    id: "retailco-expansion",
    name: "RetailCo Expansion",
    logoUrl: "/logos/retailco-expansion.svg",
    logoAlt: "RetailCo Expansion logo",
    industry: "Retail and ecommerce",
    accountTeam: "Commercial IaaS West",
    executiveConcern:
      "Digital commerce spend rose during regional expansion and leadership wants savings without slowing store launch velocity.",
    resources: [
      {
        id: "ret-cmp-001",
        resourceName: "cart-api-prod-a1",
        service: "Compute",
        compartment: "commerce-prod",
        environment: "Prod",
        region: "us-ashburn-1",
        monthlyCost: 1320,
        utilizationPct: 61,
        owner: "Platform Ops",
        costCenter: "RET-2040",
        hasLifecyclePolicy: true,
        isAttached: true,
        isPublic: false,
        notes: "Autoscaled production node pool for checkout services.",
      },
      {
        id: "ret-cmp-002",
        resourceName: "promo-engine-qa-x7",
        service: "Compute",
        compartment: "commerce-qa",
        environment: "QA",
        region: "us-ashburn-1",
        monthlyCost: 870,
        utilizationPct: 8,
        owner: "Digital QA",
        costCenter: "RET-2040",
        hasLifecyclePolicy: false,
        isAttached: true,
        isPublic: false,
        notes: "Large shape kept on through weekends for release testing.",
      },
      {
        id: "ret-cmp-003",
        resourceName: "loyalty-dev-batch",
        service: "Compute",
        compartment: "loyalty-dev",
        environment: "Dev",
        region: "us-phoenix-1",
        monthlyCost: 620,
        utilizationPct: 12,
        owner: "Loyalty Eng",
        costCenter: "",
        hasLifecyclePolicy: false,
        isAttached: true,
        isPublic: false,
        notes: "Batch host used sporadically for campaign simulation.",
      },
      {
        id: "ret-vol-004",
        resourceName: "old-pos-db-backup-vol",
        service: "Block Volume",
        compartment: "store-systems",
        environment: "Prod",
        region: "us-ashburn-1",
        monthlyCost: 430,
        utilizationPct: 0,
        owner: "Store Systems",
        costCenter: "RET-1188",
        hasLifecyclePolicy: false,
        isAttached: false,
        isPublic: false,
        notes: "Detached after migration cutover.",
      },
      {
        id: "ret-vol-005",
        resourceName: "seasonal-test-data-vol",
        service: "Block Volume",
        compartment: "analytics-test",
        environment: "Test",
        region: "us-phoenix-1",
        monthlyCost: 515,
        utilizationPct: 0,
        owner: "Data Science",
        costCenter: "",
        hasLifecyclePolicy: false,
        isAttached: false,
        isPublic: false,
        notes: "Created for peak-season model validation.",
      },
      {
        id: "ret-obj-006",
        resourceName: "catalog-image-archive",
        service: "Object Storage",
        compartment: "commerce-prod",
        environment: "Prod",
        region: "us-ashburn-1",
        monthlyCost: 1490,
        utilizationPct: 23,
        owner: "Merchandising Ops",
        costCenter: "RET-2040",
        hasLifecyclePolicy: false,
        isAttached: true,
        isPublic: true,
        notes: "Public bucket for legacy image distribution.",
      },
      {
        id: "ret-obj-007",
        resourceName: "qa-clickstream-raw",
        service: "Object Storage",
        compartment: "analytics-qa",
        environment: "QA",
        region: "us-ashburn-1",
        monthlyCost: 780,
        utilizationPct: 5,
        owner: "Analytics",
        costCenter: "RET-6601",
        hasLifecyclePolicy: false,
        isAttached: true,
        isPublic: false,
        notes: "Raw event bucket retained indefinitely.",
      },
      {
        id: "ret-adb-008",
        resourceName: "retail-insights-adw",
        service: "Autonomous Database",
        compartment: "analytics-prod",
        environment: "Prod",
        region: "us-ashburn-1",
        monthlyCost: 3110,
        utilizationPct: 48,
        owner: "Analytics",
        costCenter: "RET-6601",
        hasLifecyclePolicy: true,
        isAttached: true,
        isPublic: false,
        notes: "Executive reporting warehouse.",
      },
      {
        id: "ret-lb-009",
        resourceName: "holiday-campaign-lb",
        service: "Load Balancer",
        compartment: "marketing-test",
        environment: "Test",
        region: "us-phoenix-1",
        monthlyCost: 540,
        utilizationPct: 4,
        owner: "Marketing Tech",
        costCenter: "",
        hasLifecyclePolicy: false,
        isAttached: true,
        isPublic: true,
        notes: "Still public after campaign ended.",
      },
      {
        id: "ret-cmp-010",
        resourceName: "fraud-lab-gpu-dev",
        service: "Compute",
        compartment: "risk-dev",
        environment: "Dev",
        region: "us-ashburn-1",
        monthlyCost: 2380,
        utilizationPct: 9,
        owner: "Risk Analytics",
        costCenter: "RET-6601",
        hasLifecyclePolicy: false,
        isAttached: true,
        isPublic: false,
        notes: "GPU host used for ad hoc training.",
      },
      {
        id: "ret-oke-011",
        resourceName: "commerce-oke-prod",
        service: "OKE",
        compartment: "commerce-prod",
        environment: "Prod",
        region: "us-ashburn-1",
        monthlyCost: 1840,
        utilizationPct: 56,
        owner: "Platform Ops",
        costCenter: "RET-2040",
        hasLifecyclePolicy: true,
        isAttached: true,
        isPublic: false,
        notes: "Shared service cluster.",
      },
      {
        id: "ret-obj-012",
        resourceName: "store-video-training",
        service: "Object Storage",
        compartment: "training-prod",
        environment: "Prod",
        region: "us-phoenix-1",
        monthlyCost: 690,
        utilizationPct: 17,
        owner: "Enablement",
        costCenter: "",
        hasLifecyclePolicy: false,
        isAttached: true,
        isPublic: false,
        notes: "Training videos retained in standard tier.",
      },
    ],
  },
  {
    id: "healthsys-modernization",
    name: "HealthSys Modernization",
    logoUrl: "/logos/healthsys-modernization.svg",
    logoAlt: "HealthSys Modernization logo",
    industry: "Healthcare provider network",
    accountTeam: "Strategic Healthcare IaaS",
    executiveConcern:
      "Cloud migration is ahead of schedule, but the CIO wants tighter governance before the next clinical workload wave.",
    resources: [
      {
        id: "hlt-cmp-001",
        resourceName: "ehr-int-prod-01",
        service: "Compute",
        compartment: "clinical-prod",
        environment: "Prod",
        region: "us-ashburn-1",
        monthlyCost: 2210,
        utilizationPct: 72,
        owner: "Clinical Apps",
        costCenter: "HSP-3100",
        hasLifecyclePolicy: true,
        isAttached: true,
        isPublic: false,
        notes: "Integration host for EHR event exchange.",
      },
      {
        id: "hlt-cmp-002",
        resourceName: "claims-test-runner",
        service: "Compute",
        compartment: "claims-test",
        environment: "Test",
        region: "us-ashburn-1",
        monthlyCost: 760,
        utilizationPct: 10,
        owner: "Claims Apps",
        costCenter: "HSP-4205",
        hasLifecyclePolicy: false,
        isAttached: true,
        isPublic: false,
        notes: "Always on for batch certification cycles.",
      },
      {
        id: "hlt-cmp-003",
        resourceName: "patient-portal-dev",
        service: "Compute",
        compartment: "portal-dev",
        environment: "Dev",
        region: "us-phoenix-1",
        monthlyCost: 910,
        utilizationPct: 14,
        owner: "Digital Front Door",
        costCenter: "",
        hasLifecyclePolicy: false,
        isAttached: true,
        isPublic: true,
        notes: "Developer sandbox with temporary public endpoint.",
      },
      {
        id: "hlt-vol-004",
        resourceName: "lab-system-precutover-vol",
        service: "Block Volume",
        compartment: "clinical-migration",
        environment: "QA",
        region: "us-ashburn-1",
        monthlyCost: 690,
        utilizationPct: 0,
        owner: "Migration Factory",
        costCenter: "HSP-3100",
        hasLifecyclePolicy: false,
        isAttached: false,
        isPublic: false,
        notes: "Detached volume left after lab system cutover rehearsal.",
      },
      {
        id: "hlt-obj-005",
        resourceName: "dicom-image-archive",
        service: "Object Storage",
        compartment: "imaging-prod",
        environment: "Prod",
        region: "us-ashburn-1",
        monthlyCost: 3920,
        utilizationPct: 39,
        owner: "Imaging Services",
        costCenter: "HSP-8104",
        hasLifecyclePolicy: false,
        isAttached: true,
        isPublic: false,
        notes: "Clinical images older than 180 days remain in hot storage.",
      },
      {
        id: "hlt-obj-006",
        resourceName: "claims-remit-raw",
        service: "Object Storage",
        compartment: "claims-prod",
        environment: "Prod",
        region: "us-phoenix-1",
        monthlyCost: 840,
        utilizationPct: 18,
        owner: "Claims Apps",
        costCenter: "",
        hasLifecyclePolicy: false,
        isAttached: true,
        isPublic: false,
        notes: "Raw remit files retained indefinitely.",
      },
      {
        id: "hlt-adb-007",
        resourceName: "population-health-adw",
        service: "Autonomous Database",
        compartment: "analytics-prod",
        environment: "Prod",
        region: "us-ashburn-1",
        monthlyCost: 3480,
        utilizationPct: 58,
        owner: "Analytics COE",
        costCenter: "HSP-7000",
        hasLifecyclePolicy: true,
        isAttached: true,
        isPublic: false,
        notes: "Population health reporting database.",
      },
      {
        id: "hlt-cmp-008",
        resourceName: "ml-readmission-qa",
        service: "Compute",
        compartment: "analytics-qa",
        environment: "QA",
        region: "us-ashburn-1",
        monthlyCost: 1740,
        utilizationPct: 11,
        owner: "Analytics COE",
        costCenter: "HSP-7000",
        hasLifecyclePolicy: false,
        isAttached: true,
        isPublic: false,
        notes: "Training instance left running after model validation.",
      },
      {
        id: "hlt-lb-009",
        resourceName: "portal-dev-lb",
        service: "Load Balancer",
        compartment: "portal-dev",
        environment: "Dev",
        region: "us-phoenix-1",
        monthlyCost: 520,
        utilizationPct: 6,
        owner: "Digital Front Door",
        costCenter: "",
        hasLifecyclePolicy: false,
        isAttached: true,
        isPublic: true,
        notes: "Temporary external endpoint for partner testing.",
      },
      {
        id: "hlt-vol-010",
        resourceName: "dev-db-snapshot-volume",
        service: "Block Volume",
        compartment: "db-dev",
        environment: "Dev",
        region: "us-ashburn-1",
        monthlyCost: 360,
        utilizationPct: 0,
        owner: "Database Services",
        costCenter: "HSP-7000",
        hasLifecyclePolicy: false,
        isAttached: false,
        isPublic: false,
        notes: "Detached copy of pre-upgrade database volume.",
      },
      {
        id: "hlt-oke-011",
        resourceName: "care-team-oke-test",
        service: "OKE",
        compartment: "clinical-test",
        environment: "Test",
        region: "us-ashburn-1",
        monthlyCost: 980,
        utilizationPct: 19,
        owner: "Clinical Apps",
        costCenter: "HSP-3100",
        hasLifecyclePolicy: true,
        isAttached: true,
        isPublic: false,
        notes: "Shared test services for care-team workflow.",
      },
      {
        id: "hlt-obj-012",
        resourceName: "training-video-library",
        service: "Object Storage",
        compartment: "learning-prod",
        environment: "Prod",
        region: "us-phoenix-1",
        monthlyCost: 430,
        utilizationPct: 9,
        owner: "Learning",
        costCenter: "HSP-1150",
        hasLifecyclePolicy: true,
        isAttached: true,
        isPublic: true,
        notes: "External access used by contractor training portal.",
      },
    ],
  },
  {
    id: "finserv-non-prod-sprawl",
    name: "FinServ Non-Prod Sprawl",
    logoUrl: "/logos/finserv-non-prod-sprawl.svg",
    logoAlt: "FinServ Non-Prod Sprawl logo",
    industry: "Financial services",
    accountTeam: "Strategic Financial Services",
    executiveConcern:
      "The CTO suspects development environments are consuming run-rate budget that should be redirected to resilience work.",
    resources: [
      {
        id: "fin-cmp-001",
        resourceName: "payments-core-prod",
        service: "Compute",
        compartment: "payments-prod",
        environment: "Prod",
        region: "us-ashburn-1",
        monthlyCost: 2660,
        utilizationPct: 68,
        owner: "Payments Platform",
        costCenter: "FS-9001",
        hasLifecyclePolicy: true,
        isAttached: true,
        isPublic: false,
        notes: "Primary payments service tier.",
      },
      {
        id: "fin-cmp-002",
        resourceName: "risk-model-dev-gpu",
        service: "Compute",
        compartment: "risk-dev",
        environment: "Dev",
        region: "us-phoenix-1",
        monthlyCost: 2860,
        utilizationPct: 7,
        owner: "Risk Modeling",
        costCenter: "FS-7100",
        hasLifecyclePolicy: false,
        isAttached: true,
        isPublic: false,
        notes: "GPU shape idle outside monthly model refresh.",
      },
      {
        id: "fin-cmp-003",
        resourceName: "aml-test-grid-03",
        service: "Compute",
        compartment: "aml-test",
        environment: "Test",
        region: "us-ashburn-1",
        monthlyCost: 1180,
        utilizationPct: 13,
        owner: "Financial Crimes",
        costCenter: "",
        hasLifecyclePolicy: false,
        isAttached: true,
        isPublic: false,
        notes: "Regression grid kept on after release freeze.",
      },
      {
        id: "fin-cmp-004",
        resourceName: "mobile-qa-api",
        service: "Compute",
        compartment: "digital-qa",
        environment: "QA",
        region: "us-ashburn-1",
        monthlyCost: 690,
        utilizationPct: 16,
        owner: "Digital Banking",
        costCenter: "FS-2300",
        hasLifecyclePolicy: false,
        isAttached: true,
        isPublic: true,
        notes: "QA API endpoint opened for vendor test cycle.",
      },
      {
        id: "fin-vol-005",
        resourceName: "uat-ledger-old-volume",
        service: "Block Volume",
        compartment: "ledger-uat",
        environment: "QA",
        region: "us-ashburn-1",
        monthlyCost: 720,
        utilizationPct: 0,
        owner: "Core Banking",
        costCenter: "FS-9001",
        hasLifecyclePolicy: false,
        isAttached: false,
        isPublic: false,
        notes: "Detached after ledger data refresh.",
      },
      {
        id: "fin-vol-006",
        resourceName: "fraud-sandbox-vol",
        service: "Block Volume",
        compartment: "fraud-dev",
        environment: "Dev",
        region: "us-phoenix-1",
        monthlyCost: 410,
        utilizationPct: 0,
        owner: "Financial Crimes",
        costCenter: "",
        hasLifecyclePolicy: false,
        isAttached: false,
        isPublic: false,
        notes: "Sandbox data volume with unknown owner.",
      },
      {
        id: "fin-obj-007",
        resourceName: "statement-pdf-archive",
        service: "Object Storage",
        compartment: "statements-prod",
        environment: "Prod",
        region: "us-ashburn-1",
        monthlyCost: 2410,
        utilizationPct: 27,
        owner: "Digital Banking",
        costCenter: "FS-2300",
        hasLifecyclePolicy: false,
        isAttached: true,
        isPublic: false,
        notes: "Statement PDFs retained in standard tier.",
      },
      {
        id: "fin-obj-008",
        resourceName: "mobile-test-artifacts",
        service: "Object Storage",
        compartment: "digital-qa",
        environment: "QA",
        region: "us-ashburn-1",
        monthlyCost: 650,
        utilizationPct: 8,
        owner: "Digital Banking",
        costCenter: "FS-2300",
        hasLifecyclePolicy: false,
        isAttached: true,
        isPublic: true,
        notes: "Build artifacts temporarily shared with vendor.",
      },
      {
        id: "fin-adb-009",
        resourceName: "reg-reporting-adw",
        service: "Autonomous Database",
        compartment: "risk-prod",
        environment: "Prod",
        region: "us-ashburn-1",
        monthlyCost: 3890,
        utilizationPct: 54,
        owner: "Risk Reporting",
        costCenter: "FS-7100",
        hasLifecyclePolicy: true,
        isAttached: true,
        isPublic: false,
        notes: "Regulatory reporting data warehouse.",
      },
      {
        id: "fin-lb-010",
        resourceName: "partner-sandbox-lb",
        service: "Load Balancer",
        compartment: "partner-dev",
        environment: "Dev",
        region: "us-phoenix-1",
        monthlyCost: 560,
        utilizationPct: 5,
        owner: "Partner Integrations",
        costCenter: "",
        hasLifecyclePolicy: false,
        isAttached: true,
        isPublic: true,
        notes: "Temporary partner sandbox front door.",
      },
      {
        id: "fin-oke-011",
        resourceName: "payments-oke-prod",
        service: "OKE",
        compartment: "payments-prod",
        environment: "Prod",
        region: "us-ashburn-1",
        monthlyCost: 2140,
        utilizationPct: 63,
        owner: "Payments Platform",
        costCenter: "FS-9001",
        hasLifecyclePolicy: true,
        isAttached: true,
        isPublic: false,
        notes: "Payments microservices cluster.",
      },
      {
        id: "fin-cmp-012",
        resourceName: "treasury-qa-worker",
        service: "Compute",
        compartment: "treasury-qa",
        environment: "QA",
        region: "us-ashburn-1",
        monthlyCost: 840,
        utilizationPct: 9,
        owner: "Treasury Tech",
        costCenter: "FS-3300",
        hasLifecyclePolicy: false,
        isAttached: true,
        isPublic: false,
        notes: "QA worker used during end-of-month cycles.",
      },
    ],
  },
];
